const crypto = require("crypto");

const ROLES = ["engenheiro", "tecnico", "admin"];
const TYPES = ["temperatura", "umidadeSolo", "umidadeAr", "chuva"];
const required = ["SUPABASE_URL", "JWT_SECRET", "IOT_API_KEY", "FRONTEND_ORIGIN"];
function config() {
  const missing = required.filter((key) => !process.env[key]);
  const key = process.env.SUPABASE_SECRET_KEY || process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!key) missing.push("SUPABASE_SECRET_KEY");
  if (missing.length) throw new Error(`Configuracao ausente: ${missing.join(", ")}`);
  if (process.env.JWT_SECRET.length < 32) throw new Error("JWT_SECRET inseguro.");
  const origins = process.env.FRONTEND_ORIGIN.split(",").map((v) => v.trim()).filter(Boolean);
  origins.push(`http://localhost:${process.env.PORT || 3000}`, `http://127.0.0.1:${process.env.PORT || 3000}`);
  return { url: process.env.SUPABASE_URL.replace(/\/$/, ""), key, jwt: process.env.JWT_SECRET, iot: process.env.IOT_API_KEY, origins: [...new Set(origins)] };
}
function originFor(req, c) { const origin = req.headers.origin; return origin && c.origins.includes(origin) ? origin : undefined; }
function reply(res, status, data, origin) { res.statusCode = status; res.setHeader("Content-Type", "application/json; charset=utf-8"); res.setHeader("X-Content-Type-Options", "nosniff"); res.setHeader("Cache-Control", "no-store"); if (origin) { res.setHeader("Access-Control-Allow-Origin", origin); res.setHeader("Vary", "Origin"); } res.end(JSON.stringify(data)); }
function parseBody(req) { return new Promise((resolve, reject) => { let raw = "", size = 0; req.on("data", (chunk) => { size += chunk.length; if (size > 16384) { reject(new Error("Corpo muito grande.")); req.destroy(); } else raw += chunk; }); req.on("end", () => { try { resolve(raw ? JSON.parse(raw) : {}); } catch { reject(new Error("JSON invalido.")); } }); req.on("error", reject); }); }
const b64 = (v) => Buffer.from(JSON.stringify(v)).toString("base64url");
function createToken(user, secret) { const h = b64({ alg: "HS256", typ: "JWT" }), p = b64({ sub: user.id, matricula: user.matricula, nome: user.nome, perfil: user.perfil, iat: Math.floor(Date.now() / 1000), exp: Math.floor(Date.now() / 1000) + 28800 }); return `${h}.${p}.${crypto.createHmac("sha256", secret).update(`${h}.${p}`).digest("base64url")}`; }
function authenticated(req, secret) { try { const [h, p, s] = String(req.headers.authorization || "").replace(/^Bearer\s+/i, "").split("."); if (!h || !p || !s) return null; const expected = crypto.createHmac("sha256", secret).update(`${h}.${p}`).digest(), supplied = Buffer.from(s, "base64url"); if (supplied.length !== expected.length || !crypto.timingSafeEqual(supplied, expected)) return null; const user = JSON.parse(Buffer.from(p, "base64url").toString("utf8")); return user.exp > Date.now() / 1000 && ROLES.includes(user.perfil) ? user : null; } catch { return null; } }
function hashPassword(password) { const rounds = 210000, salt = crypto.randomBytes(16).toString("hex"), hash = crypto.pbkdf2Sync(password, salt, rounds, 32, "sha256").toString("hex"); return `pbkdf2$${rounds}$${salt}$${hash}`; }
function passwordOk(password, stored) { const [kind, rounds, salt, hash] = String(stored || "").split("$"); if (kind !== "pbkdf2" || !/^\d+$/.test(rounds) || !salt || !/^[a-f0-9]{64}$/i.test(hash)) return false; const actual = crypto.pbkdf2Sync(password, salt, Number(rounds), 32, "sha256").toString("hex"); return crypto.timingSafeEqual(Buffer.from(actual), Buffer.from(hash)); }
async function db(c, table, method = "GET", data, query = "") { const response = await fetch(`${c.url}/rest/v1/${table}${query}`, { method, headers: { apikey: c.key, Authorization: `Bearer ${c.key}`, "Content-Type": "application/json", Prefer: method === "POST" || method === "PATCH" ? "return=representation,resolution=merge-duplicates" : "" }, body: data === undefined ? undefined : JSON.stringify(data) }); if (!response.ok) throw new Error("Falha no banco de dados."); return response.status === 204 ? [] : response.json(); }
const hits = new Map();
function rateLimit(req, maximum) { const ip = String(req.headers["x-forwarded-for"] || req.socket.remoteAddress || "?").split(",")[0].trim(), now = Date.now(), state = hits.get(ip) || { at: now, count: 0 }; if (now - state.at > 60000) { state.at = now; state.count = 0; } state.count++; hits.set(ip, state); return state.count <= maximum; }
function text(v, max = 160) { return typeof v === "string" && v.trim() && v.trim().length <= max ? v.trim() : null; }
function date(v) { return /^\d{4}-\d{2}-\d{2}$/.test(String(v)) ? v : null; }
function telemetryValid(d) { return text(d.sensorId, 80) && text(d.talhao, 40) && TYPES.includes(d.tipo) && Number.isFinite(Number(d.valor)) && Math.abs(Number(d.valor)) <= 1000000 && (!d.timestamp || !Number.isNaN(Date.parse(d.timestamp))); }

module.exports = async (req, res) => {
  let c; try { c = config(); } catch (error) { console.error(error.message); return reply(res, 503, { mensagem: "API ainda nao configurada." }); }
  const origin = originFor(req, c);
  if (req.headers.origin && !origin) return reply(res, 403, { mensagem: "Origem nao permitida." });
  if (req.method === "OPTIONS") { if (!origin) return reply(res, 403, { mensagem: "Origem nao permitida." }); res.writeHead(204, { "Access-Control-Allow-Origin": origin, "Access-Control-Allow-Headers": "Content-Type, Authorization, X-IoT-Key", "Access-Control-Allow-Methods": "GET, POST, OPTIONS", "Access-Control-Max-Age": "600", Vary: "Origin" }); return res.end(); }
  if (!rateLimit(req, req.url.includes("/login") ? 10 : 120)) return reply(res, 429, { mensagem: "Muitas requisicoes." }, origin);
  const route = new URL(req.url, "http://localhost").pathname.replace(/^\/api/, "") || "/";
  try {
    if (req.method === "GET" && route === "/health") { try { await db(c, "organizacao", "GET", undefined, "?select=id&limit=1"); return reply(res, 200, { sucesso: true, banco: true }, origin); } catch { return reply(res, 503, { sucesso: false, banco: false, mensagem: "Banco nao inicializado ou indisponivel." }, origin); } }
    if (req.method === "POST" && route === "/login") { const d = await parseBody(req), matricula = text(d.matricula, 40), senha = typeof d.senha === "string" ? d.senha : ""; if (!matricula || senha.length < 8 || senha.length > 256) return reply(res, 401, { mensagem: "Matricula ou senha invalida." }, origin); const users = await db(c, "usuarios", "GET", undefined, `?matricula=eq.${encodeURIComponent(matricula)}&select=id,matricula,nome_completo,perfil,senha_hash,status&limit=1`), user = users[0]; if (!user || user.status !== "ativo" || !passwordOk(senha, user.senha_hash)) return reply(res, 401, { mensagem: "Matricula ou senha invalida." }, origin); const safe = { id: user.id, matricula: user.matricula, nome: user.nome_completo, perfil: user.perfil === "administrador" ? "admin" : user.perfil }; return reply(res, 200, { sucesso: true, usuario: safe, token: createToken(safe, c.jwt) }, origin); }
    if (req.method === "POST" && route === "/iot/telemetria") { const supplied = Buffer.from(String(req.headers["x-iot-key"] || "")), expected = Buffer.from(c.iot); if (supplied.length !== expected.length || !crypto.timingSafeEqual(supplied, expected)) return reply(res, 401, { mensagem: "Credencial IoT invalida." }, origin); const d = await parseBody(req); if (!telemetryValid(d)) return reply(res, 400, { mensagem: "Telemetria invalida." }, origin); const device = (await db(c, "dispositivo", "GET", undefined, `?id_externo=eq.${encodeURIComponent(d.sensorId)}&status=neq.desativado&select=id,talhao_id&limit=1`))[0]; if (!device) return reply(res, 403, { mensagem: "Dispositivo nao autorizado." }, origin); const plot = (await db(c, "talhao", "GET", undefined, `?id=eq.${device.talhao_id}&select=codigo&limit=1`))[0]; if (!plot || plot.codigo !== d.talhao) return reply(res, 403, { mensagem: "Dispositivo nao pertence ao talhao." }, origin); const sensor = (await db(c, "sensor", "GET", undefined, `?dispositivo_id=eq.${device.id}&codigo_metrica=eq.${encodeURIComponent(d.tipo)}&status=eq.ativo&select=id,unidade&limit=1`))[0]; if (!sensor) return reply(res, 403, { mensagem: "Sensor ou metrica nao autorizada." }, origin); const when = d.timestamp || new Date().toISOString(); await db(c, "leitura_sensor", "POST", { sensor_id:sensor.id, dispositivo_id:device.id, coletado_em:when, valor:Number(d.valor), unidade:text(d.unidade,20)||sensor.unidade, carga_bruta:d }); await db(c, `dispositivo?id=eq.${device.id}`, "PATCH", { ultimo_sinal_em:when, status:"online" }); return reply(res, 201, { sucesso:true }, origin); }
    const user = authenticated(req, c.jwt); if (!user) return reply(res, 401, { mensagem: "Nao autorizado." }, origin);
    if (req.method === "GET" && ["/painel-tecnico", "/painel-engenheiro"].includes(route)) { const [plots, devices, sensors, readings, inspections] = await Promise.all([db(c,"talhao","GET",undefined,"?select=id,codigo,nome,area_hectares&order=codigo"),db(c,"dispositivo","GET",undefined,"?select=id,id_externo,talhao_id,status,ultimo_sinal_em"),db(c,"sensor","GET",undefined,"?select=id,id_externo,dispositivo_id,codigo_metrica,unidade,status"),db(c,"v_ultima_leitura_sensor","GET",undefined,"?select=*&limit=500"),db(c,"inspecao","GET",undefined,"?select=*&order=inspecionado_em.desc&limit=30")]); const readingBySensor=new Map(readings.map(r=>[r.sensor_id,r])); const deviceById=new Map(devices.map(d=>[d.id,d])); const sensorRows=sensors.map(s=>{const d=deviceById.get(s.dispositivo_id), r=readingBySensor.get(s.id);return {sensor:s.id_externo,talhao:d&&plots.find(p=>p.id===d.talhao_id)?.codigo,status:d?.status==="offline"?"Offline":"Online",leitura:r?`${r.valor} ${r.unidade}`:"Sem leitura",comunicacao:r?.coletado_em||d?.ultimo_sinal_em,id:s.id,tipo:s.codigo_metrica,valor:r?.valor,unidade:s.unidade};}); const talhoes=plots.map(p=>{const s=sensorRows.find(x=>x.talhao===p.codigo), critical=!s||s.status==="Offline"||(s.tipo==="umidadeSolo"&&Number(s.valor)<30), attention=s&&s.tipo==="umidadeSolo"&&Number(s.valor)<40;return {id:p.codigo,cultura:p.nome||p.codigo,area:`${p.area_hectares} hectares`,sensor:s?.sensor,leitura:s?.leitura||"Sem leitura",situacao:critical?"Critico":attention?"Atencao":"Normal",prioridade:critical?"Checar sensor e irrigacao":attention?"Verificar umidade do solo":"Rotina de acompanhamento"};}); return reply(res,200,{talhoes,sensores:sensorRows,inspecoes:inspections.map(i=>({data:i.inspecionado_em?.slice(0,10),talhao:plots.find(p=>p.id===i.talhao_id)?.codigo,situacao:i.status?.[0]?.toUpperCase()+i.status?.slice(1),problemas:i.descricao_problema,observacoes:i.observacoes})),plantios:[],tarefas:talhoes.filter(p=>p.situacao!=="Normal").map(p=>({talhao:p.id,prioridade:p.situacao==="Critico"?"Critica":"Atencao",atividade:p.prioridade})),alertas:[]},origin); }
    if (req.method === "POST" && route === "/plantios") { if (!["engenheiro", "admin"].includes(user.perfil)) return reply(res, 403, { mensagem: "Sem permissao." }, origin); const d = await parseBody(req); if (!["produto", "variedade", "talhao", "solo"].every((k) => text(d[k])) || !date(d.dataPlantio) || !date(d.dataColheita) || !Number.isFinite(Number(d.area)) || Number(d.area) <= 0) return reply(res, 400, { mensagem: "Dados de plantio invalidos." }, origin); await db(c, "plantios", "POST", { produto: text(d.produto), variedade: text(d.variedade), talhao: text(d.talhao), area: Number(d.area), solo: text(d.solo), data_plantio: d.dataPlantio, data_colheita: d.dataColheita, usuario_id: user.sub }); return reply(res, 201, { sucesso: true }, origin); }
    if (req.method === "POST" && ["/inspecoes", "/ocorrencias", "/sensores/problemas"].includes(route)) { if (!["tecnico", "admin"].includes(user.perfil)) return reply(res, 403, { mensagem: "Sem permissao." }, origin); const d = await parseBody(req), table = route === "/inspecoes" ? "inspecoes" : route === "/ocorrencias" ? "ocorrencias" : "problemas_sensor"; if (!text(d.talhao) || (table === "inspecoes" && (!date(d.data) || !["Normal", "Atencao", "Critico"].includes(d.situacao))) || (table === "ocorrencias" && !text(d.tipo)) || (table === "problemas_sensor" && (!text(d.sensor) || !date(d.data) || !text(d.problema)))) return reply(res, 400, { mensagem: "Dados invalidos." }, origin); await db(c, table, "POST", { ...d, usuario_id: user.sub }); return reply(res, 201, { sucesso: true }, origin); }
    if (req.method === "GET" && route === "/admin/usuarios") { if (user.perfil !== "admin") return reply(res, 403, { mensagem: "Sem permissao." }, origin); const rows = await db(c, "usuarios", "GET", undefined, "?select=id,matricula,nome_completo,perfil,cargo,status,criado_em&order=matricula"); return reply(res, 200, { usuarios: rows.map((r) => ({ id:r.id, matricula:r.matricula, nome:r.nome_completo, perfil:r.perfil === "administrador" ? "admin" : r.perfil, cargo:r.cargo, ativo:r.status === "ativo", created_at:r.criado_em })) }, origin); }
    if (req.method === "POST" && route === "/admin/usuarios") { if (user.perfil !== "admin") return reply(res, 403, { mensagem: "Sem permissao." }, origin); const d = await parseBody(req); if (!text(d.matricula, 40) || !text(d.nome) || !text(d.cargo) || !ROLES.includes(d.perfil) || !["ativo", "inativo"].includes(d.status) || typeof d.senha !== "string" || d.senha.length < 12 || d.senha.length > 256) return reply(res, 400, { mensagem: "Dados invalidos: senha temporaria deve ter ao menos 12 caracteres." }, origin); const org = (await db(c, "organizacao", "GET", undefined, "?select=id&order=criado_em&limit=1"))[0]; if (!org) return reply(res, 503, { mensagem:"Organizacao nao configurada." }, origin); await db(c, "usuarios", "POST", { organizacao_id:org.id, matricula:text(d.matricula,40), nome_completo:text(d.nome), cargo:text(d.cargo), perfil:d.perfil === "admin" ? "administrador" : d.perfil, status:d.status, senha_hash:hashPassword(d.senha) }); return reply(res, 201, { sucesso:true }, origin); }
    return reply(res, 404, { mensagem: "Rota nao encontrada." }, origin);
  } catch (error) { console.error(`${req.method} ${route}:`, error.message); return reply(res, 500, { mensagem: "Erro interno." }, origin); }
};
